[package]
name = "kitkat"
version = "0.0.1"
authors = ["JoeyHops <me@joeyhops.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1"
